//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAportesTerminales.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AportesTerminalesEntities : DbContext
    {
        public AportesTerminalesEntities()
            : base("name=AportesTerminalesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_deleteAcuerdoCompraCabecera_Result> sp_deleteAcuerdoCompraCabecera(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_deleteAcuerdoCompraCabecera_Result>("sp_deleteAcuerdoCompraCabecera", idParameter);
        }
    
        public virtual ObjectResult<sp_getBaseRecepcionesCabecera_Result> sp_getBaseRecepcionesCabecera()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getBaseRecepcionesCabecera_Result>("sp_getBaseRecepcionesCabecera");
        }
    
        public virtual ObjectResult<sp_crucepxqcabecera_sel_Result> sp_crucepxqcabecera_sel(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_crucepxqcabecera_sel_Result>("sp_crucepxqcabecera_sel", idParameter);
        }
    
        public virtual ObjectResult<sp_postCruceMarca_Result> sp_postCruceMarca(string idPxQDetalleEntregado, string idPxQDetallePendiente)
        {
            var idPxQDetalleEntregadoParameter = idPxQDetalleEntregado != null ?
                new ObjectParameter("idPxQDetalleEntregado", idPxQDetalleEntregado) :
                new ObjectParameter("idPxQDetalleEntregado", typeof(string));
    
            var idPxQDetallePendienteParameter = idPxQDetallePendiente != null ?
                new ObjectParameter("idPxQDetallePendiente", idPxQDetallePendiente) :
                new ObjectParameter("idPxQDetallePendiente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_postCruceMarca_Result>("sp_postCruceMarca", idPxQDetalleEntregadoParameter, idPxQDetallePendienteParameter);
        }
    
        public virtual ObjectResult<sp_deleteCruceLineaDuplicada_Result> sp_deleteCruceLineaDuplicada(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_deleteCruceLineaDuplicada_Result>("sp_deleteCruceLineaDuplicada", idParameter);
        }
    
        public virtual ObjectResult<sp_getCruceLineasRepetidas_Result> sp_getCruceLineasRepetidas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getCruceLineasRepetidas_Result>("sp_getCruceLineasRepetidas");
        }
    
        public virtual ObjectResult<sp_postBaseRecepcion_Result> sp_postBaseRecepcion(string ownerEmail, string nombreArchivo, string fechaCarga, string rutaArchivo, string periodo, string xml)
        {
            var ownerEmailParameter = ownerEmail != null ?
                new ObjectParameter("ownerEmail", ownerEmail) :
                new ObjectParameter("ownerEmail", typeof(string));
    
            var nombreArchivoParameter = nombreArchivo != null ?
                new ObjectParameter("nombreArchivo", nombreArchivo) :
                new ObjectParameter("nombreArchivo", typeof(string));
    
            var fechaCargaParameter = fechaCarga != null ?
                new ObjectParameter("fechaCarga", fechaCarga) :
                new ObjectParameter("fechaCarga", typeof(string));
    
            var rutaArchivoParameter = rutaArchivo != null ?
                new ObjectParameter("rutaArchivo", rutaArchivo) :
                new ObjectParameter("rutaArchivo", typeof(string));
    
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            var xmlParameter = xml != null ?
                new ObjectParameter("xml", xml) :
                new ObjectParameter("xml", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_postBaseRecepcion_Result>("sp_postBaseRecepcion", ownerEmailParameter, nombreArchivoParameter, fechaCargaParameter, rutaArchivoParameter, periodoParameter, xmlParameter);
        }
    
        public virtual ObjectResult<sp_getAcuerdoCompraCabecera_Result> sp_getAcuerdoCompraCabecera()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAcuerdoCompraCabecera_Result>("sp_getAcuerdoCompraCabecera");
        }
    
        public virtual ObjectResult<sp_postAcuerdoCompra_Result> sp_postAcuerdoCompra(string ownerEmail, string nombreArchivo, string fechaCarga, string rutaArchivo, string periodo, string xml)
        {
            var ownerEmailParameter = ownerEmail != null ?
                new ObjectParameter("ownerEmail", ownerEmail) :
                new ObjectParameter("ownerEmail", typeof(string));
    
            var nombreArchivoParameter = nombreArchivo != null ?
                new ObjectParameter("nombreArchivo", nombreArchivo) :
                new ObjectParameter("nombreArchivo", typeof(string));
    
            var fechaCargaParameter = fechaCarga != null ?
                new ObjectParameter("fechaCarga", fechaCarga) :
                new ObjectParameter("fechaCarga", typeof(string));
    
            var rutaArchivoParameter = rutaArchivo != null ?
                new ObjectParameter("rutaArchivo", rutaArchivo) :
                new ObjectParameter("rutaArchivo", typeof(string));
    
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            var xmlParameter = xml != null ?
                new ObjectParameter("xml", xml) :
                new ObjectParameter("xml", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_postAcuerdoCompra_Result>("sp_postAcuerdoCompra", ownerEmailParameter, nombreArchivoParameter, fechaCargaParameter, rutaArchivoParameter, periodoParameter, xmlParameter);
        }
    
        public virtual ObjectResult<sp_postCrucePxQDetalle_Result> sp_postCrucePxQDetalle(Nullable<int> id, string ncVir, string estadoVir, string estadoAcreditadoVir, string ncFc, string estadoFc, string estadoAcreditadoFc, string ncIncoterm, string estadoIncoterm, string estadoAcreditadoIncoterm, string factFc, string estadoFactFc, string estadoAcreditadoFactFc)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var ncVirParameter = ncVir != null ?
                new ObjectParameter("NcVir", ncVir) :
                new ObjectParameter("NcVir", typeof(string));
    
            var estadoVirParameter = estadoVir != null ?
                new ObjectParameter("EstadoVir", estadoVir) :
                new ObjectParameter("EstadoVir", typeof(string));
    
            var estadoAcreditadoVirParameter = estadoAcreditadoVir != null ?
                new ObjectParameter("EstadoAcreditadoVir", estadoAcreditadoVir) :
                new ObjectParameter("EstadoAcreditadoVir", typeof(string));
    
            var ncFcParameter = ncFc != null ?
                new ObjectParameter("NcFc", ncFc) :
                new ObjectParameter("NcFc", typeof(string));
    
            var estadoFcParameter = estadoFc != null ?
                new ObjectParameter("EstadoFc", estadoFc) :
                new ObjectParameter("EstadoFc", typeof(string));
    
            var estadoAcreditadoFcParameter = estadoAcreditadoFc != null ?
                new ObjectParameter("EstadoAcreditadoFc", estadoAcreditadoFc) :
                new ObjectParameter("EstadoAcreditadoFc", typeof(string));
    
            var ncIncotermParameter = ncIncoterm != null ?
                new ObjectParameter("NcIncoterm", ncIncoterm) :
                new ObjectParameter("NcIncoterm", typeof(string));
    
            var estadoIncotermParameter = estadoIncoterm != null ?
                new ObjectParameter("EstadoIncoterm", estadoIncoterm) :
                new ObjectParameter("EstadoIncoterm", typeof(string));
    
            var estadoAcreditadoIncotermParameter = estadoAcreditadoIncoterm != null ?
                new ObjectParameter("EstadoAcreditadoIncoterm", estadoAcreditadoIncoterm) :
                new ObjectParameter("EstadoAcreditadoIncoterm", typeof(string));
    
            var factFcParameter = factFc != null ?
                new ObjectParameter("FactFc", factFc) :
                new ObjectParameter("FactFc", typeof(string));
    
            var estadoFactFcParameter = estadoFactFc != null ?
                new ObjectParameter("EstadoFactFc", estadoFactFc) :
                new ObjectParameter("EstadoFactFc", typeof(string));
    
            var estadoAcreditadoFactFcParameter = estadoAcreditadoFactFc != null ?
                new ObjectParameter("EstadoAcreditadoFactFc", estadoAcreditadoFactFc) :
                new ObjectParameter("EstadoAcreditadoFactFc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_postCrucePxQDetalle_Result>("sp_postCrucePxQDetalle", idParameter, ncVirParameter, estadoVirParameter, estadoAcreditadoVirParameter, ncFcParameter, estadoFcParameter, estadoAcreditadoFcParameter, ncIncotermParameter, estadoIncotermParameter, estadoAcreditadoIncotermParameter, factFcParameter, estadoFactFcParameter, estadoAcreditadoFactFcParameter);
        }
    
        public virtual ObjectResult<sp_getCrucePxQDetalleTipoAporte_sel_Result> sp_getCrucePxQDetalleTipoAporte_sel(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getCrucePxQDetalleTipoAporte_sel_Result>("sp_getCrucePxQDetalleTipoAporte_sel", idParameter);
        }
    
        public virtual ObjectResult<sp_deleteBaseRecepcionCabecera_Result> sp_deleteBaseRecepcionCabecera(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_deleteBaseRecepcionCabecera_Result>("sp_deleteBaseRecepcionCabecera", idParameter);
        }
    
        public virtual ObjectResult<sp_baserecepcion_rel_acuerdocompra_sel_Result> sp_baserecepcion_rel_acuerdocompra_sel(string ownerEmail)
        {
            var ownerEmailParameter = ownerEmail != null ?
                new ObjectParameter("ownerEmail", ownerEmail) :
                new ObjectParameter("ownerEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_baserecepcion_rel_acuerdocompra_sel_Result>("sp_baserecepcion_rel_acuerdocompra_sel", ownerEmailParameter);
        }
    
        public virtual ObjectResult<sp_getLineaDeuda_sel_Result> sp_getLineaDeuda_sel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getLineaDeuda_sel_Result>("sp_getLineaDeuda_sel");
        }
    
        public virtual ObjectResult<sp_postNotaCredito_Result> sp_postNotaCredito(string ownerEmail, string nc, string idsDetalleCruce)
        {
            var ownerEmailParameter = ownerEmail != null ?
                new ObjectParameter("ownerEmail", ownerEmail) :
                new ObjectParameter("ownerEmail", typeof(string));
    
            var ncParameter = nc != null ?
                new ObjectParameter("nc", nc) :
                new ObjectParameter("nc", typeof(string));
    
            var idsDetalleCruceParameter = idsDetalleCruce != null ?
                new ObjectParameter("idsDetalleCruce", idsDetalleCruce) :
                new ObjectParameter("idsDetalleCruce", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_postNotaCredito_Result>("sp_postNotaCredito", ownerEmailParameter, ncParameter, idsDetalleCruceParameter);
        }
    
        public virtual ObjectResult<sp_getNotaCredito_sel_Result> sp_getNotaCredito_sel(Nullable<int> idNc)
        {
            var idNcParameter = idNc.HasValue ?
                new ObjectParameter("idNc", idNc) :
                new ObjectParameter("idNc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getNotaCredito_sel_Result>("sp_getNotaCredito_sel", idNcParameter);
        }
    
        public virtual ObjectResult<sp_postNotaCreditoPagada_Result> sp_postNotaCreditoPagada(string ids, string idsNc)
        {
            var idsParameter = ids != null ?
                new ObjectParameter("ids", ids) :
                new ObjectParameter("ids", typeof(string));
    
            var idsNcParameter = idsNc != null ?
                new ObjectParameter("idsNc", idsNc) :
                new ObjectParameter("idsNc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_postNotaCreditoPagada_Result>("sp_postNotaCreditoPagada", idsParameter, idsNcParameter);
        }
    
        public virtual ObjectResult<sp_getNotaCreditoByCruce_sel_Result> sp_getNotaCreditoByCruce_sel(Nullable<int> idDetalle)
        {
            var idDetalleParameter = idDetalle.HasValue ?
                new ObjectParameter("idDetalle", idDetalle) :
                new ObjectParameter("idDetalle", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getNotaCreditoByCruce_sel_Result>("sp_getNotaCreditoByCruce_sel", idDetalleParameter);
        }
    
        public virtual ObjectResult<sp_PostNotaCreditoAceptada_Result> sp_PostNotaCreditoAceptada(string idNc, string aceptarParcialmente, string observaciones)
        {
            var idNcParameter = idNc != null ?
                new ObjectParameter("idNc", idNc) :
                new ObjectParameter("idNc", typeof(string));
    
            var aceptarParcialmenteParameter = aceptarParcialmente != null ?
                new ObjectParameter("aceptarParcialmente", aceptarParcialmente) :
                new ObjectParameter("aceptarParcialmente", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PostNotaCreditoAceptada_Result>("sp_PostNotaCreditoAceptada", idNcParameter, aceptarParcialmenteParameter, observacionesParameter);
        }
    
        public virtual ObjectResult<sp_postNotaCreditoContabilidad_Result> sp_postNotaCreditoContabilidad(string idNcConta, string urlCc)
        {
            var idNcContaParameter = idNcConta != null ?
                new ObjectParameter("idNcConta", idNcConta) :
                new ObjectParameter("idNcConta", typeof(string));
    
            var urlCcParameter = urlCc != null ?
                new ObjectParameter("urlCc", urlCc) :
                new ObjectParameter("urlCc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_postNotaCreditoContabilidad_Result>("sp_postNotaCreditoContabilidad", idNcContaParameter, urlCcParameter);
        }
    
        public virtual ObjectResult<sp_deleteRegistrosPendientes_Result> sp_deleteRegistrosPendientes(string idPxQDetallePendiente)
        {
            var idPxQDetallePendienteParameter = idPxQDetallePendiente != null ?
                new ObjectParameter("idPxQDetallePendiente", idPxQDetallePendiente) :
                new ObjectParameter("idPxQDetallePendiente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_deleteRegistrosPendientes_Result>("sp_deleteRegistrosPendientes", idPxQDetallePendienteParameter);
        }
    
        public virtual ObjectResult<sp_getLineasNotaCredito_Result> sp_getLineasNotaCredito(Nullable<int> idLineaNc)
        {
            var idLineaNcParameter = idLineaNc.HasValue ?
                new ObjectParameter("idLineaNc", idLineaNc) :
                new ObjectParameter("idLineaNc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getLineasNotaCredito_Result>("sp_getLineasNotaCredito", idLineaNcParameter);
        }
    
        public virtual ObjectResult<sp_postNotaCreditoNotificacion_Result> sp_postNotaCreditoNotificacion(string idNcNotificacion)
        {
            var idNcNotificacionParameter = idNcNotificacion != null ?
                new ObjectParameter("idNcNotificacion", idNcNotificacion) :
                new ObjectParameter("idNcNotificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_postNotaCreditoNotificacion_Result>("sp_postNotaCreditoNotificacion", idNcNotificacionParameter);
        }
    
        public virtual ObjectResult<sp_postNotaCreditoRechazada_Result> sp_postNotaCreditoRechazada(string idCruce, string idNc, string observacionesRechazo)
        {
            var idCruceParameter = idCruce != null ?
                new ObjectParameter("idCruce", idCruce) :
                new ObjectParameter("idCruce", typeof(string));
    
            var idNcParameter = idNc != null ?
                new ObjectParameter("idNc", idNc) :
                new ObjectParameter("idNc", typeof(string));
    
            var observacionesRechazoParameter = observacionesRechazo != null ?
                new ObjectParameter("observacionesRechazo", observacionesRechazo) :
                new ObjectParameter("observacionesRechazo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_postNotaCreditoRechazada_Result>("sp_postNotaCreditoRechazada", idCruceParameter, idNcParameter, observacionesRechazoParameter);
        }
    
        public virtual ObjectResult<sp_getLineaNotaCreditoContabilidad_Result> sp_getLineaNotaCreditoContabilidad(Nullable<int> idLineaNc)
        {
            var idLineaNcParameter = idLineaNc.HasValue ?
                new ObjectParameter("idLineaNc", idLineaNc) :
                new ObjectParameter("idLineaNc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getLineaNotaCreditoContabilidad_Result>("sp_getLineaNotaCreditoContabilidad", idLineaNcParameter);
        }
    
        public virtual ObjectResult<sp_getLineasNotaCreditoCompras_sel_Result> sp_getLineasNotaCreditoCompras_sel(Nullable<int> idDetalle)
        {
            var idDetalleParameter = idDetalle.HasValue ?
                new ObjectParameter("idDetalle", idDetalle) :
                new ObjectParameter("idDetalle", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getLineasNotaCreditoCompras_sel_Result>("sp_getLineasNotaCreditoCompras_sel", idDetalleParameter);
        }
    
        public virtual ObjectResult<sp_getLineasNotaCreditoHistorial_sel_Result> sp_getLineasNotaCreditoHistorial_sel(string ownerEmail)
        {
            var ownerEmailParameter = ownerEmail != null ?
                new ObjectParameter("ownerEmail", ownerEmail) :
                new ObjectParameter("ownerEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getLineasNotaCreditoHistorial_sel_Result>("sp_getLineasNotaCreditoHistorial_sel", ownerEmailParameter);
        }
    
        public virtual ObjectResult<sp_PostSustento_Result> sp_PostSustento(string ownerEmail, string sus, string idsCruceCabMarca)
        {
            var ownerEmailParameter = ownerEmail != null ?
                new ObjectParameter("ownerEmail", ownerEmail) :
                new ObjectParameter("ownerEmail", typeof(string));
    
            var susParameter = sus != null ?
                new ObjectParameter("sus", sus) :
                new ObjectParameter("sus", typeof(string));
    
            var idsCruceCabMarcaParameter = idsCruceCabMarca != null ?
                new ObjectParameter("idsCruceCabMarca", idsCruceCabMarca) :
                new ObjectParameter("idsCruceCabMarca", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PostSustento_Result>("sp_PostSustento", ownerEmailParameter, susParameter, idsCruceCabMarcaParameter);
        }
    
        public virtual ObjectResult<sp_getActasSamsung_sel_Result> sp_getActasSamsung_sel(Nullable<bool> esSamsung)
        {
            var esSamsungParameter = esSamsung.HasValue ?
                new ObjectParameter("esSamsung", esSamsung) :
                new ObjectParameter("esSamsung", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getActasSamsung_sel_Result>("sp_getActasSamsung_sel", esSamsungParameter);
        }
    
        public virtual ObjectResult<sp_getSustento_sel_Result> sp_getSustento_sel(Nullable<bool> esSamsung)
        {
            var esSamsungParameter = esSamsung.HasValue ?
                new ObjectParameter("esSamsung", esSamsung) :
                new ObjectParameter("esSamsung", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getSustento_sel_Result>("sp_getSustento_sel", esSamsungParameter);
        }
    
        public virtual ObjectResult<sp_postSustentoAprobado_Result> sp_postSustentoAprobado(string ownerEmail, string idSus)
        {
            var ownerEmailParameter = ownerEmail != null ?
                new ObjectParameter("ownerEmail", ownerEmail) :
                new ObjectParameter("ownerEmail", typeof(string));
    
            var idSusParameter = idSus != null ?
                new ObjectParameter("idSus", idSus) :
                new ObjectParameter("idSus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_postSustentoAprobado_Result>("sp_postSustentoAprobado", ownerEmailParameter, idSusParameter);
        }
    
        public virtual ObjectResult<sp_postSustentoRechazado_Result> sp_postSustentoRechazado(string ownerEmail, string idSus, string observaciones)
        {
            var ownerEmailParameter = ownerEmail != null ?
                new ObjectParameter("ownerEmail", ownerEmail) :
                new ObjectParameter("ownerEmail", typeof(string));
    
            var idSusParameter = idSus != null ?
                new ObjectParameter("idSus", idSus) :
                new ObjectParameter("idSus", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_postSustentoRechazado_Result>("sp_postSustentoRechazado", ownerEmailParameter, idSusParameter, observacionesParameter);
        }
    
        public virtual ObjectResult<sp_postSustentoFacturacion_Result> sp_postSustentoFacturacion(string ownerEmail, string idPxQDetalle, string fac, string idSus)
        {
            var ownerEmailParameter = ownerEmail != null ?
                new ObjectParameter("ownerEmail", ownerEmail) :
                new ObjectParameter("ownerEmail", typeof(string));
    
            var idPxQDetalleParameter = idPxQDetalle != null ?
                new ObjectParameter("idPxQDetalle", idPxQDetalle) :
                new ObjectParameter("idPxQDetalle", typeof(string));
    
            var facParameter = fac != null ?
                new ObjectParameter("fac", fac) :
                new ObjectParameter("fac", typeof(string));
    
            var idSusParameter = idSus != null ?
                new ObjectParameter("idSus", idSus) :
                new ObjectParameter("idSus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_postSustentoFacturacion_Result>("sp_postSustentoFacturacion", ownerEmailParameter, idPxQDetalleParameter, facParameter, idSusParameter);
        }
    
        public virtual ObjectResult<sp_getActasOtraMarca_sel_Result> sp_getActasOtraMarca_sel(Nullable<int> idLinea)
        {
            var idLineaParameter = idLinea.HasValue ?
                new ObjectParameter("idLinea", idLinea) :
                new ObjectParameter("idLinea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getActasOtraMarca_sel_Result>("sp_getActasOtraMarca_sel", idLineaParameter);
        }
    
        public virtual ObjectResult<sp_postSustentoFinalizarCampana_Result> sp_postSustentoFinalizarCampana(string idSus, string idsCruceCabMarca)
        {
            var idSusParameter = idSus != null ?
                new ObjectParameter("idSus", idSus) :
                new ObjectParameter("idSus", typeof(string));
    
            var idsCruceCabMarcaParameter = idsCruceCabMarca != null ?
                new ObjectParameter("idsCruceCabMarca", idsCruceCabMarca) :
                new ObjectParameter("idsCruceCabMarca", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_postSustentoFinalizarCampana_Result>("sp_postSustentoFinalizarCampana", idSusParameter, idsCruceCabMarcaParameter);
        }
    
        public virtual ObjectResult<sp_getSustentoOm_sel_Result> sp_getSustentoOm_sel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getSustentoOm_sel_Result>("sp_getSustentoOm_sel");
        }
    
        public virtual ObjectResult<sp_getSustentoOmByActas_sel_Result> sp_getSustentoOmByActas_sel(Nullable<int> idCabMar)
        {
            var idCabMarParameter = idCabMar.HasValue ?
                new ObjectParameter("idCabMar", idCabMar) :
                new ObjectParameter("idCabMar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getSustentoOmByActas_sel_Result>("sp_getSustentoOmByActas_sel", idCabMarParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_getPermisosUsuarios_sel(string correo)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_getPermisosUsuarios_sel", correoParameter);
        }
    
        public virtual ObjectResult<sp_getMarcas_Result> sp_getMarcas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getMarcas_Result>("sp_getMarcas");
        }
    
        public virtual ObjectResult<sp_getFactura_sel_Result> sp_getFactura_sel(Nullable<bool> esSamsung)
        {
            var esSamsungParameter = esSamsung.HasValue ?
                new ObjectParameter("esSamsung", esSamsung) :
                new ObjectParameter("esSamsung", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getFactura_sel_Result>("sp_getFactura_sel", esSamsungParameter);
        }
    
        public virtual ObjectResult<sp_getDebtsPaid_sel_Result> sp_getDebtsPaid_sel(Nullable<int> idDetalle)
        {
            var idDetalleParameter = idDetalle.HasValue ?
                new ObjectParameter("idDetalle", idDetalle) :
                new ObjectParameter("idDetalle", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getDebtsPaid_sel_Result>("sp_getDebtsPaid_sel", idDetalleParameter);
        }
    
        public virtual ObjectResult<sp_getSustentoDeudasPxQ_Result> sp_getSustentoDeudasPxQ(Nullable<int> idSustento)
        {
            var idSustentoParameter = idSustento.HasValue ?
                new ObjectParameter("idSustento", idSustento) :
                new ObjectParameter("idSustento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getSustentoDeudasPxQ_Result>("sp_getSustentoDeudasPxQ", idSustentoParameter);
        }
    
        public virtual ObjectResult<sp_postDeudaPagadaAcreditada_Result> sp_postDeudaPagadaAcreditada(string idDeudasPxQ)
        {
            var idDeudasPxQParameter = idDeudasPxQ != null ?
                new ObjectParameter("idDeudasPxQ", idDeudasPxQ) :
                new ObjectParameter("idDeudasPxQ", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_postDeudaPagadaAcreditada_Result>("sp_postDeudaPagadaAcreditada", idDeudasPxQParameter);
        }
    
        public virtual int sp_token(string token)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_token", tokenParameter);
        }
    
        public virtual ObjectResult<sp_getFacturaSustento_sel_Result> sp_getFacturaSustento_sel(Nullable<int> idSus)
        {
            var idSusParameter = idSus.HasValue ?
                new ObjectParameter("idSus", idSus) :
                new ObjectParameter("idSus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getFacturaSustento_sel_Result>("sp_getFacturaSustento_sel", idSusParameter);
        }
    
        public virtual ObjectResult<sp_getNotaCredito_Marca_sel_Result> sp_getNotaCredito_Marca_sel(string ownerEmail)
        {
            var ownerEmailParameter = ownerEmail != null ?
                new ObjectParameter("ownerEmail", ownerEmail) :
                new ObjectParameter("ownerEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getNotaCredito_Marca_sel_Result>("sp_getNotaCredito_Marca_sel", ownerEmailParameter);
        }
    
        public virtual ObjectResult<sp_validarLogin_Result> sp_validarLogin(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_validarLogin_Result>("sp_validarLogin", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_deudasCruce_sel_Result> sp_deudasCruce_sel(string ownerEmail)
        {
            var ownerEmailParameter = ownerEmail != null ?
                new ObjectParameter("ownerEmail", ownerEmail) :
                new ObjectParameter("ownerEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_deudasCruce_sel_Result>("sp_deudasCruce_sel", ownerEmailParameter);
        }
    
        public virtual ObjectResult<sp_deleteNotaCredito_Result> sp_deleteNotaCredito(string ids, string idsNc)
        {
            var idsParameter = ids != null ?
                new ObjectParameter("ids", ids) :
                new ObjectParameter("ids", typeof(string));
    
            var idsNcParameter = idsNc != null ?
                new ObjectParameter("idsNc", idsNc) :
                new ObjectParameter("idsNc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_deleteNotaCredito_Result>("sp_deleteNotaCredito", idsParameter, idsNcParameter);
        }
    
        public virtual ObjectResult<sp_postDeudaValidada_Result> sp_postDeudaValidada(string ownerEmail, string ids, string deudaSamsung)
        {
            var ownerEmailParameter = ownerEmail != null ?
                new ObjectParameter("ownerEmail", ownerEmail) :
                new ObjectParameter("ownerEmail", typeof(string));
    
            var idsParameter = ids != null ?
                new ObjectParameter("ids", ids) :
                new ObjectParameter("ids", typeof(string));
    
            var deudaSamsungParameter = deudaSamsung != null ?
                new ObjectParameter("deudaSamsung", deudaSamsung) :
                new ObjectParameter("deudaSamsung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_postDeudaValidada_Result>("sp_postDeudaValidada", ownerEmailParameter, idsParameter, deudaSamsungParameter);
        }
    
        public virtual ObjectResult<sp_getDeudaValidada_Marca_sel_Result> sp_getDeudaValidada_Marca_sel(string ownerEmail)
        {
            var ownerEmailParameter = ownerEmail != null ?
                new ObjectParameter("ownerEmail", ownerEmail) :
                new ObjectParameter("ownerEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getDeudaValidada_Marca_sel_Result>("sp_getDeudaValidada_Marca_sel", ownerEmailParameter);
        }
    }
}
